services:
  _defaults:
    autowire: true
    autoconfigure: true

  Anboo\Profiler\Bundle\EventSubscriber\:
    resource: '../../EventSubscriber'
    tags: ['kernel.event_subscriber']

  Anboo\Profiler\Bundle\EventSubscriber\CommandProfileSubscriber:
    bind:
      $ignoreCommandsRegex: '%anboo_profiler.ignore_commands%'
    tags: ['kernel.event_subscriber']

  Anboo\Profiler\Bundle\EventSubscriber\ControllerProfileSubscriber:
    bind:
      $ignoreRoutesRegex: '%anboo_profiler.ignore_routes%'
    tags: ['kernel.event_subscriber']